#!/usr/bin/env python

import sys
import requests

def get_status(user, repo):
    response = requests.get(f"https://github.com/{user}/{repo}/actions/workflows/python-app.yml/badge.svg")
    if response.status_code == 200:
        badge = response.content.decode('utf-8')
        return "passing" in badge
    else:
        return None

def gitbuildcheck(user_repo, shame=False):
    user, repo = user_repo.split("/")
    status = get_status(user, repo)
    if status is None:
        print(f"Unable to check status for {user}/{repo}")
        sys.exit(1)
    elif status:
        print(f"{user}/{repo} build/test status: passing")
        sys.exit(0)
    else:
        print(f"{user}/{repo} build/test status: failing")
        if shame:
            import subprocess
            subprocess.run(['sh', 'runsiren.sh'])
        sys.exit(1)

if __name__ == "__main__":
    shame = "--shame" in sys.argv
    user_repo = sys.argv[-1]
    gitbuildcheck(user_repo, shame)
